#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focus_follows_pointer true

bspc config border_width 1
bspc config window_gap 10

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
